### ISSUE TITLE
confused about cert.pem

### ISSUE THREAD

**Issue by wangjie-fourth** [httptoolkit/jvm-http-proxy-agent#1]
Hi, i get here from [this article](https://httptoolkit.tech/blog/how-to-intercept-debug-java-http/). I think this tool are great for developer.Thanks for you build this.

when i try use it on command line, i am confused about `cert.pem`. how can i find this file?

I don’t know much about Java’s SSL and network configuration. and i try to google this,  i could not find anything satisfying. so do you hava any good article([like above](https://httptoolkit.tech/blog/how-to-intercept-debug-java-http/)) to explain this?

Thank you in advance for your attention.

**Comment by pimterry** [comment]
Hi @wangjie-fourth. Cert.pem is the public certificate of the certificate authority (CA) that you want to trust for HTTPS, in PEM format.

If you're trying to intercept HTTPS traffic, whichever HTTPS intercepting proxy you're using will have generated this. By configuring this agent with the proxy's certificate, it ensures that your Java application trusts that certificate for HTTPS, and so the proxy is allowed to inspect and edit secure traffic. Does that make sense?

If that's not enough for your issue, I'm happy to point you in the right direction, but it would be useful to know more context about what tools you're using and what exactly you're trying to do.

**Comment by ExerciseBook** [comment]
I met this problem this afternoon, so I patched this application.

Download Mozilla CA Bundle https://curl.se/docs/caextract.html and use it!

---

There are 2 years since you post this issue. I am not sure whether you need it now.

**Comment by pimterry** [comment]
I'm not clear whether these two issues are actually related, but the latter CA bundle issue is now fixed and included in the latest release (v1.3.4) and the former has been stale here for quite some time. I'm going to close this for now, but feel free to open a new issue if you're still having any problems.
