### ISSUE TITLE
Attaching at Startup Example Issue: `|` would parse as a shell metacharacter on unix terminal

### ISSUE THREAD

**Issue by cryptohazey** [httptoolkit/jvm-http-proxy-agent#10]
Referring to the "Attaching at Startup example", unix terminal would read `|` as a shell meta- character

Example Given:
`java -javaagent:./agent.jar=127.0.0.1|8000|/path/to/cert.pem -jar ./application.jar`

Example output on MacOS Unix terminal:
```
 % java -javaagent:./agent.jar=127.0.0.1|8000|/path/to/cert.pem -jar ./application.jar
zsh: no such file or directory: /path/to/cert.pem
zsh: command not found: 8000
```

Am i using the agent.jar the right way?

**Comment by pimterry** [comment]
Very true! Yes in a shell you'll need to quote that option. I've just [updated](https://github.com/httptoolkit/jvm-http-proxy-agent/commit/184782680ed3b8011bdd35eba6a92dda1de581a9) the example in the README:

```bash
java -javaagent:./agent.jar="127.0.0.1|8000|/path/to/cert.pem" -jar ./application.jar
```

I think that should resolve this, so I'll close this issue, but let me know if you're still having trouble.

**Comment by cryptohazey** [comment]
Thank you!
